eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true  #使用ip注册到注册中心
server:
  port: 9001
spring:
  application:
    name: ZUUL_PLAT
zuul:
  routes:
    aigou_plat: /login/**   #映射
  ignored-services: "*"
  prefix: /aigou  #前缀